---
train_datasets:
    FDTD2D:
        split: "train"
        skip: 5

test_datasets:
    FDTD2D:
        split: "test"
        skip: 5
        
model:
    name: Cnn

train:
    device: "cuda"
    num_workers: 16
    loss: l1
    optimizer: AdamW
    lr: 3e-4
    warm_up_steps: 1000  # Leave blank if no warm up is used
    batch_size_per_device: 16
    test_every_n_steps: 1000
    save_every_n_steps: 2000
    training_steps: 20000
    resume_ckpt_path:  # Leave blank if train from scratch